apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mortgage
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: mortgage
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: mortgage
    repoURL: https://github.com/avaleror/application-examples.git
    targetRevision: master
  syncPolicy:
    automated:
      selfHeal: true

