apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pacman
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: pacman
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: book-import
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: master
  syncPolicy:
    automated:
      selfHeal: true

